# Generated by Django 4.1.7 on 2023-02-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houselistingmodel',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
